version: '3.3'

services:
  nginx:
    image: nginx:1.17.0
    restart: always      
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d  
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web      
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  web:
    restart: always
    depends_on:
      - db
    build: .
    ports:
      - 8082:8082
  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: webapp 
      MYSQL_ROOT_PASSWORD: 12345

